services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/:/var/lib/postgresql/data/
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql

  gen-txns-csv:
    build:
      context: ./
      dockerfile: cmd/gen-txns-csv/Dockerfile
    volumes:
      - ./files:/files
    restart: "no"
    command: "exit 0"

  proc-txns-csv:
    build:
      context: ./
      dockerfile: cmd/proc-txns-csv/Dockerfile
    volumes:
      - ./files:/files
    restart: "no"
    command: "exit 0"
