// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package dao

import (
	"context"
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts
    (first_name, last_name, email, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING account_id
`

type CreateAccountParams struct {
	FirstName string
	LastName  string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT account_id, first_name, last_name, email, created_at, updated_at FROM accounts WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions
    (account_id, operation, amount, performed_at, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING transaction_id
`

type InsertTransactionParams struct {
	AccountID   int64
	Operation   TxOperationType
	Amount      decimal.Decimal
	PerformedAt time.Time
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.AccountID,
		arg.Operation,
		arg.Amount,
		arg.PerformedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var transaction_id int64
	err := row.Scan(&transaction_id)
	return transaction_id, err
}
